- hosts: application_server
  vars:
    tomcat_version: 10.1.19
    tomcat_base_name: apache-tomcat-{{ tomcat_version }}

  tasks:
    - name: Install java
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
        update_cache: true
      become: true
      become_method: ansible.builtin.sudo

    - name: Setup Group tomcat
      ansible.builtin.group:
        name: tomcat
      become: true
      become_method: ansible.builtin.sudo

    - name: Setup User tomcat
      ansible.builtin.user:
        name: tomcat
        group: tomcat
      become: true
      become_method: ansible.builtin.sudo

    - name: Setup User Ansible
      ansible.builtin.user:
        name: vagrant
        group: tomcat
      become: true
      become_method: ansible.builtin.sudo


    - name: Download current Tomcat version {{ tomcat_version }}
      ansible.builtin.get_url:
        url: "http://archive.apache.org/dist/tomcat/tomcat-10/v{{ tomcat_version }}/bin/{{ tomcat_base_name }}.tar.gz"
        dest: "/tmp"
      delegate_to: localhost

    - ansible.builtin.file: # noqa 502
        name: /opt
        mode: 0777
        owner: tomcat
        group: tomcat
      become: true
      become_method: ansible.builtin.sudo

    - name: Install Tomcat {{ tomcat_version }}
      ansible.builtin.unarchive:
        src: "/tmp/{{ tomcat_base_name }}.tar.gz"
        dest: "/opt"
        creates: "/opt/{{ tomcat_base_name }}"
        owner: tomcat
        group: tomcat
      become: true
      become_method: ansible.builtin.sudo

    - name: Set link to tomcat {{ tomcat_version }}
      ansible.builtin.file:
        src: "/opt/{{ tomcat_base_name }}"
        dest: "/opt/tomcat"
        owner: tomcat
        group: tomcat
        state: link
        force: true
      become: true
      become_method: ansible.builtin.sudo

