- hosts: application_server
  vars:
    tomcat_version: 9.0.27
    tomcat_base_name: apache-tomcat-{{ tomcat_version }}

  tasks:
    - name: install java
      apt:
        name: openjdk-8-jdk
        state: present
      become: yes
      become_method: sudo

    - name: Setup Group tomcat
      group:
        name: tomcat
      become: yes
      become_method: sudo

    - name: Setup User tomcat
      user:
        name: tomcat
        group: tomcat
      become: yes
      become_method: sudo

    - name: Setup User Ansible
      user:
        name: vagrant
        group: tomcat
      become: yes
      become_method: sudo


    - name: Download current Tomcat {{ tomcat_version }} version
      get_url:
        url: "http://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/{{ tomcat_base_name }}.tar.gz"
        dest: "/tmp"
      delegate_to: localhost

    - file: # noqa 502
        name: /opt
        mode: 0777
        owner: tomcat
        group: tomcat
      become: yes
      become_method: sudo

    - name: Install Tomcat {{ tomcat_version }}
      unarchive:
        src: "/tmp/{{ tomcat_base_name }}.tar.gz"
        dest: "/opt"
        creates: "/opt/{{ tomcat_base_name }}"
        owner: tomcat
        group: tomcat
      become: yes
      become_method: sudo

    - name: Set link to tomcat {{ tomcat_version }}
      file:
        src: "/opt/{{ tomcat_base_name }}"
        dest: "/opt/tomcat"
        owner: tomcat
        group: tomcat
        state: link
        force: yes
      become: yes
      become_method: sudo

    - find: paths="/opt/{{ tomcat_base_name }}/bin" patterns="*.sh" # noqa 502
      register: result

    - name: ensure tomcat scripts are executable
      file:
        name: "{{ item.path }}"
        mode: 0755
      with_items: '{{ result.files }}'
      become: yes
      become_method: sudo
